import type {
  AppStat,
  Category,
  FeedPost,
  LeaderboardEntry,
  PersonProfile,
  Tool,
  ToolRelease,
  TrendEvent,
} from "@/lib/product-model";

export const categories: Category[] = [
  {
    slug: "reasoning",
    name: "Reasoning",
    tagline: "Models that win on thoughtfulness and reliability",
    description: "Track flagship reasoning systems, benchmark shifts, and operator sentiment.",
    accent: "emerald",
    icon: "R",
  },
  {
    slug: "coding",
    name: "Coding",
    tagline: "The models shipping real work",
    description: "Watch code models, agents, toolchains, and workflow debates in one lane.",
    accent: "cyan",
    icon: "C",
  },
  {
    slug: "video",
    name: "Video",
    tagline: "The frontier for motion and cinematic generation",
    description: "See the latest model jumps, style control progress, and workflow breakdowns.",
    accent: "amber",
    icon: "V",
  },
  {
    slug: "image",
    name: "Image",
    tagline: "Fast shifts in style, control, and consistency",
    description: "Follow image generation, editing, prompting, and commercial tool changes.",
    accent: "pink",
    icon: "I",
  },
  {
    slug: "agents",
    name: "Agents",
    tagline: "Automation that actually gets used",
    description: "Compare the tools people trust for deep work, retrieval, and multistep execution.",
    accent: "violet",
    icon: "A",
  },
  {
    slug: "news",
    name: "News",
    tagline: "The launches and updates that truly matter",
    description: "A signal layer for releases, funding, open-source drops, and company moves.",
    accent: "red",
    icon: "N",
  },
];

export const tools: Tool[] = [
  {
    id: "tool-openai-o4",
    slug: "o4-reasoning",
    name: "o4 Reasoning",
    company: "OpenAI",
    category: "reasoning",
    summary: "High-trust chain-of-thought style reasoning for research, planning, and operator workflows.",
    website: "https://openai.com",
    pricing: "Premium API pricing",
    bestFor: ["research", "planning", "high-context reasoning"],
    strengths: ["consistency under ambiguity", "strong tool reasoning", "reliable long-form work"],
    weaknesses: ["cost sensitivity", "slower than lightweight models"],
    changeSummary: "Jumped after a strong evaluation cycle on complex agent tasks.",
    discussionVolume: 1482,
    savedCount: 5930,
  },
  {
    id: "tool-codex-spark",
    slug: "codex-spark",
    name: "Codex Spark",
    company: "OpenAI",
    category: "coding",
    summary: "Fast code generation and repair model tuned for iterative engineering loops.",
    website: "https://openai.com",
    pricing: "Mid-tier API pricing",
    bestFor: ["fast iteration", "repo assistance", "UI refactors"],
    strengths: ["speed", "good patch quality", "strong repo context use"],
    weaknesses: ["needs guidance on architecture", "can overfit local patterns"],
    changeSummary: "Rising on usage velocity with engineers using it for rapid code loops.",
    discussionVolume: 2131,
    savedCount: 7440,
  },
  {
    id: "tool-veo-next",
    slug: "veo-next",
    name: "Veo Next",
    company: "Google",
    category: "video",
    summary: "High-end video generation with cinematic motion and impressive scene coherence.",
    website: "https://deepmind.google",
    pricing: "Enterprise / waitlist",
    bestFor: ["cinematic shots", "camera movement", "high fidelity demos"],
    strengths: ["motion quality", "shot coherence", "color fidelity"],
    weaknesses: ["limited access", "slow iteration"],
    changeSummary: "Dominating conversation after new filmmaker-side results.",
    discussionVolume: 2987,
    savedCount: 11120,
  },
  {
    id: "tool-flux-studio",
    slug: "flux-studio",
    name: "Flux Studio",
    company: "Black Forest Labs",
    category: "image",
    summary: "Image generation tuned for editorial clarity, composition control, and style fidelity.",
    website: "https://blackforestlabs.ai",
    pricing: "Freemium",
    bestFor: ["concept art", "editorial imagery", "fast style exploration"],
    strengths: ["style control", "composition", "wide community knowledge"],
    weaknesses: ["hands and text still uneven", "can drift across iterative edits"],
    changeSummary: "Holding top spot after balanced updates rather than flashy launch spikes.",
    discussionVolume: 1775,
    savedCount: 6520,
  },
  {
    id: "tool-orbit-agent",
    slug: "orbit-agent",
    name: "Orbit Agent",
    company: "Orbit",
    category: "agents",
    summary: "Agent workspace blending retrieval, planning, and browser execution into repeatable loops.",
    website: "https://orbit.example.com",
    pricing: "$49 / month",
    bestFor: ["multi-step research", "ops automations", "agent teams"],
    strengths: ["task memory", "workflow repeatability", "strong operator UX"],
    weaknesses: ["setup overhead", "complex permissions"],
    changeSummary: "New entrant with sharp word of mouth among AI operators.",
    discussionVolume: 942,
    savedCount: 2315,
  },
  {
    id: "tool-signal-wire",
    slug: "signal-wire-news",
    name: "Signal Wire",
    company: "Signal",
    category: "news",
    summary: "High-signal AI news digest with fast curation, summaries, and cross-source linking.",
    website: "https://signal.example.com",
    pricing: "Free + pro digest",
    bestFor: ["daily catch-up", "launch tracking", "source aggregation"],
    strengths: ["speed", "curation", "clear summaries"],
    weaknesses: ["less original reporting", "can cluster around hype cycles"],
    changeSummary: "Breaking into the news leaderboard thanks to strong daily retention.",
    discussionVolume: 515,
    savedCount: 1840,
  },
];

export const leaderboardEntries: LeaderboardEntry[] = [
  {
    id: "lb-reasoning-o4",
    category: "reasoning",
    lens: "overall",
    toolSlug: "o4-reasoning",
    rank: 1,
    previousRank: 2,
    score: 97,
    editorialWeight: 96,
    communityWeight: 93,
    velocityWeight: 91,
    rationale: "Strongest balance of trust, breadth, and tool use in high-context reasoning work.",
    movement: "up",
  },
  {
    id: "lb-coding-codex",
    category: "coding",
    lens: "overall",
    toolSlug: "codex-spark",
    rank: 1,
    previousRank: 1,
    score: 95,
    editorialWeight: 91,
    communityWeight: 94,
    velocityWeight: 98,
    rationale: "Winning on daily engineering throughput and fix velocity rather than benchmark theater.",
    movement: "steady",
  },
  {
    id: "lb-video-veo",
    category: "video",
    lens: "overall",
    toolSlug: "veo-next",
    rank: 1,
    previousRank: 1,
    score: 98,
    editorialWeight: 97,
    communityWeight: 95,
    velocityWeight: 96,
    rationale: "Most convincing cinematic output and strongest narrative motion in current public discussion.",
    movement: "steady",
  },
  {
    id: "lb-image-flux",
    category: "image",
    lens: "overall",
    toolSlug: "flux-studio",
    rank: 1,
    previousRank: 1,
    score: 94,
    editorialWeight: 93,
    communityWeight: 92,
    velocityWeight: 86,
    rationale: "Still the most dependable option for teams that need high-quality image output fast.",
    movement: "steady",
  },
  {
    id: "lb-agents-orbit",
    category: "agents",
    lens: "overall",
    toolSlug: "orbit-agent",
    rank: 3,
    previousRank: null,
    score: 88,
    editorialWeight: 84,
    communityWeight: 82,
    velocityWeight: 97,
    rationale: "A fresh breakout tool with unusually strong early operator retention and discussion quality.",
    movement: "new",
  },
  {
    id: "lb-news-wire",
    category: "news",
    lens: "overall",
    toolSlug: "signal-wire-news",
    rank: 2,
    previousRank: 5,
    score: 85,
    editorialWeight: 84,
    communityWeight: 79,
    velocityWeight: 92,
    rationale: "The fastest-moving AI news source in this week’s cross-category catch-up behavior.",
    movement: "up",
  },
  {
    id: "lb-coding-codex-value",
    category: "coding",
    lens: "value",
    toolSlug: "codex-spark",
    rank: 2,
    previousRank: 3,
    score: 89,
    editorialWeight: 88,
    communityWeight: 87,
    velocityWeight: 91,
    rationale: "Not the cheapest, but the speed-to-acceptable-output ratio is pushing it up the value chart.",
    movement: "up",
  },
  {
    id: "lb-video-veo-creative",
    category: "video",
    lens: "creative",
    toolSlug: "veo-next",
    rank: 1,
    previousRank: 1,
    score: 99,
    editorialWeight: 99,
    communityWeight: 94,
    velocityWeight: 94,
    rationale: "The best current option for visually ambitious work where craft and motion matter most.",
    movement: "steady",
  },
];

export const people: PersonProfile[] = [
  {
    id: "person-rhea",
    handle: "rheacodes",
    name: "Rhea Codes",
    role: "Staff engineer / evaluator",
    expertise: ["coding", "agents"],
    credibilityLabel: "High-signal operator",
    bio: "Breaks down code models and agent stacks by what actually ships, not what benchmarks well.",
    followerCount: 48300,
    postCount: 216,
  },
  {
    id: "person-noah",
    handle: "noahframes",
    name: "Noah Frames",
    role: "AI filmmaker",
    expertise: ["video", "image"],
    credibilityLabel: "Filmmaker workflows",
    bio: "Tracks prompt control, consistency, and production-ready video generation for cinematic teams.",
    followerCount: 27400,
    postCount: 144,
  },
  {
    id: "person-sana",
    handle: "sanaops",
    name: "Sana Ops",
    role: "AI researcher",
    expertise: ["reasoning", "news"],
    credibilityLabel: "Research translator",
    bio: "Turns dense model updates into practical takeaways for operators, builders, and product teams.",
    followerCount: 61200,
    postCount: 332,
  },
];

export const posts: FeedPost[] = [
  {
    id: "post-video-1",
    category: "video",
    postType: "comparison",
    authorHandle: "noahframes",
    title: "Veo Next vs current film pipelines",
    body: "The gap is no longer just raw fidelity. The real change is camera confidence, motion continuity, and less cleanup between shots.",
    linkedToolSlugs: ["veo-next"],
    externalUrl: null,
    reactionCount: 1182,
    commentCount: 214,
    createdAt: "2026-03-22T10:15:00.000Z",
  },
  {
    id: "post-coding-1",
    category: "coding",
    postType: "workflow",
    authorHandle: "rheacodes",
    title: "My current coding stack after two weeks of tool testing",
    body: "Fast editor loops matter more than raw benchmark rank. The best setup right now is the one that keeps patch-review cycles tight.",
    linkedToolSlugs: ["codex-spark"],
    externalUrl: null,
    reactionCount: 928,
    commentCount: 146,
    createdAt: "2026-03-22T08:45:00.000Z",
  },
  {
    id: "post-news-1",
    category: "news",
    postType: "news",
    authorHandle: "sanaops",
    title: "The launch everyone is talking about today",
    body: "This is one of those updates where the product change matters less than the downstream market pressure it creates.",
    linkedToolSlugs: ["signal-wire-news"],
    externalUrl: "https://signal.example.com/story",
    reactionCount: 684,
    commentCount: 89,
    createdAt: "2026-03-22T09:30:00.000Z",
  },
];

export const trendEvents: TrendEvent[] = [
  {
    id: "trend-veo",
    category: "video",
    label: "Cinematic motion quality jumps again",
    summary: "Video creators are reshuffling workflows after stronger camera movement and scene continuity tests.",
    movement: "up",
    signalScore: 98,
    references: ["veo-next", "noahframes"],
  },
  {
    id: "trend-codex",
    category: "coding",
    label: "Coding models are splitting by speed vs depth",
    summary: "Teams are increasingly treating coding ranks as multiple leaderboards instead of one universal winner.",
    movement: "up",
    signalScore: 92,
    references: ["codex-spark", "rheacodes"],
  },
  {
    id: "trend-orbit",
    category: "agents",
    label: "Agents are back in operator conversations",
    summary: "The strongest agent products are no longer selling hype. They are selling repeatable workflows and memory.",
    movement: "new",
    signalScore: 89,
    references: ["orbit-agent"],
  },
];

export const releases: ToolRelease[] = [
  {
    id: "rel-veo-next",
    toolSlug: "veo-next",
    label: "Shot control update",
    note: "Improved camera path handling and more stable multi-shot continuity.",
    releasedAt: "2026-03-21T18:00:00.000Z",
  },
  {
    id: "rel-codex-spark",
    toolSlug: "codex-spark",
    label: "Repo pass refinement",
    note: "Better file selection and less noisy patch generation in larger projects.",
    releasedAt: "2026-03-20T16:20:00.000Z",
  },
];

export const appStats: AppStat[] = [
  {
    label: "Tracked tools",
    value: "184",
    note: "Across ranking, release, and discussion surfaces",
  },
  {
    label: "Signals today",
    value: "2.8k",
    note: "Weighted reactions, posts, saves, and release moves",
  },
  {
    label: "Category rooms",
    value: "6",
    note: "Each with its own feed, ranks, and top voices",
  },
];

export const toolsBySlug = Object.fromEntries(tools.map((tool) => [tool.slug, tool]));
export const peopleByHandle = Object.fromEntries(people.map((person) => [person.handle, person]));
export const categoriesBySlug = Object.fromEntries(categories.map((category) => [category.slug, category]));
